"""add is_verified to sprint session and locked_at to sprint bid

Revision ID: 698b5fc86b48
Revises: 7ab42d19e801
Create Date: 2026-08-01 19:58:00.070752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '698b5fc86b48'
down_revision = '7ab42d19e801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elite_sprint_bid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locked_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('elite_sprint_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.create_index(batch_op.f('ix_elite_sprint_session_is_verified'), ['is_verified'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elite_sprint_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_elite_sprint_session_is_verified'))
        batch_op.drop_column('is_verified')

    with op.batch_alter_table('elite_sprint_bid', schema=None) as batch_op:
        batch_op.drop_column('locked_at')

    # ### end Alembic commands ###
