"""initial production schema

Revision ID: b6463543bae2
Revises: 
Create Date: 2026-07-25 03:17:10.956682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6463543bae2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream', sa.String(length=30), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('point_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_point_rule_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_point_rule_stream'), ['stream'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active_account', sa.Boolean(), nullable=False),
    sa.Column('profile_completed', sa.Boolean(), nullable=False),
    sa.Column('register_number', sa.String(length=80), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('leetcode_url', sa.String(length=500), nullable=True),
    sa.Column('preferred_domain', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_register_number'), ['register_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)

    op.create_table('support_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=180), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_message_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_message_student_id'), ['student_id'], unique=False)

    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_code', sa.String(length=30), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('reference_links', sa.Text(), nullable=True),
    sa.Column('reward_points', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attachment_path', sa.String(length=500), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('deadline_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_task_code'), ['task_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_task_task_type'), ['task_type'], unique=False)

    op.create_table('point_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('point_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_point_transaction_approved_by'), ['approved_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_point_transaction_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_point_transaction_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_point_transaction_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_point_transaction_type'), ['type'], unique=False)

    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('github_link', sa.String(length=500), nullable=True),
    sa.Column('drive_link', sa.String(length=500), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('admin_remarks', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submission_reviewed_by'), ['reviewed_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_submission_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_submission_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submission_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submission_task_id'))
        batch_op.drop_index(batch_op.f('ix_submission_student_id'))
        batch_op.drop_index(batch_op.f('ix_submission_status'))
        batch_op.drop_index(batch_op.f('ix_submission_reviewed_by'))

    op.drop_table('submission')
    with op.batch_alter_table('point_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_point_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_point_transaction_task_id'))
        batch_op.drop_index(batch_op.f('ix_point_transaction_student_id'))
        batch_op.drop_index(batch_op.f('ix_point_transaction_created_at'))
        batch_op.drop_index(batch_op.f('ix_point_transaction_approved_by'))

    op.drop_table('point_transaction')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_task_type'))
        batch_op.drop_index(batch_op.f('ix_task_task_code'))
        batch_op.drop_index(batch_op.f('ix_task_status'))
        batch_op.drop_index(batch_op.f('ix_task_created_by'))
        batch_op.drop_index(batch_op.f('ix_task_category'))

    op.drop_table('task')
    with op.batch_alter_table('support_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_message_student_id'))
        batch_op.drop_index(batch_op.f('ix_support_message_status'))

    op.drop_table('support_message')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_index(batch_op.f('ix_user_register_number'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_department'))

    op.drop_table('user')
    with op.batch_alter_table('point_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_point_rule_stream'))
        batch_op.drop_index(batch_op.f('ix_point_rule_code'))

    op.drop_table('point_rule')
    # ### end Alembic commands ###
