"""add has_golden_star to elite_sprint_bid

Revision ID: c1dedf6a7303
Revises: 698b5fc86b48
Create Date: 2026-08-01 20:05:23.881730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1dedf6a7303'
down_revision = '698b5fc86b48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elite_sprint_bid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_golden_star', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.create_index(batch_op.f('ix_elite_sprint_bid_has_golden_star'), ['has_golden_star'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elite_sprint_bid', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_elite_sprint_bid_has_golden_star'))
        batch_op.drop_column('has_golden_star')

    # ### end Alembic commands ###
