"""elite sprint verification v2

Revision ID: f977847837d7
Revises: c1dedf6a7303
Create Date: 2026-08-02 15:46:04.791754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f977847837d7'
down_revision = 'c1dedf6a7303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sprint_verification_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('planned_task_ids', sa.Text(), nullable=True),
    sa.Column('submitted_task_ids', sa.Text(), nullable=True),
    sa.Column('missing_task_ids', sa.Text(), nullable=True),
    sa.Column('penalty_points', sa.Integer(), nullable=True),
    sa.Column('earned_golden_star', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'student_id', name='uq_sprint_verify_session_student')
    )
    with op.batch_alter_table('sprint_verification_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sprint_verification_result_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sprint_verification_result_student_id'), ['student_id'], unique=False)

    with op.batch_alter_table('elite_sprint_bid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_ids', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))

    with op.batch_alter_table('elite_sprint_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bidding_starts_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('bidding_ends_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completion_ends_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('verification_mode', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_elite_sprint_session_bidding_ends_at'), ['bidding_ends_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_elite_sprint_session_bidding_starts_at'), ['bidding_starts_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_elite_sprint_session_completion_ends_at'), ['completion_ends_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_elite_sprint_session_is_verified'), ['is_verified'], unique=False)
        batch_op.create_index(batch_op.f('ix_elite_sprint_session_verified'), ['verified'], unique=False)

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sprint_session_id', sa.Integer(), nullable=True))
        batch_op.create_index('ix_submission_student_task_date_status', ['student_id', 'task_id', 'submission_date', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_submission_sprint_session_id'), ['sprint_session_id'], unique=False)
        batch_op.create_foreign_key('fk_submission_sprint_session_id_elite_sprint_session', 'elite_sprint_session', ['sprint_session_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('golden_stars', sa.Integer(), nullable=False, server_default=sa.text("0")))
        batch_op.add_column(sa.Column('penalty_flags', sa.Integer(), nullable=False, server_default=sa.text("0")))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('penalty_flags')
        batch_op.drop_column('golden_stars')

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_constraint('fk_submission_sprint_session_id_elite_sprint_session', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_submission_sprint_session_id'))
        batch_op.create_index(batch_op.f('ix_submission_student_task_date_status'), ['student_id', 'task_id', 'submission_date', 'status'], unique=False)
        batch_op.drop_column('sprint_session_id')

    with op.batch_alter_table('elite_sprint_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_elite_sprint_session_verified'))
        batch_op.drop_index(batch_op.f('ix_elite_sprint_session_is_verified'))
        batch_op.drop_index(batch_op.f('ix_elite_sprint_session_is_verified'))
        batch_op.drop_index(batch_op.f('ix_elite_sprint_session_completion_ends_at'))
        batch_op.drop_index(batch_op.f('ix_elite_sprint_session_bidding_starts_at'))
        batch_op.drop_index(batch_op.f('ix_elite_sprint_session_bidding_ends_at'))
        batch_op.drop_column('verification_mode')
        batch_op.drop_column('verified_at')
        batch_op.drop_column('verified')
        batch_op.drop_column('completion_ends_at')
        batch_op.drop_column('bidding_ends_at')
        batch_op.drop_column('bidding_starts_at')

    with op.batch_alter_table('elite_sprint_bid', schema=None) as batch_op:
        batch_op.drop_column('task_ids')

    with op.batch_alter_table('sprint_verification_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sprint_verification_result_student_id'))
        batch_op.drop_index(batch_op.f('ix_sprint_verification_result_session_id'))

    op.drop_table('sprint_verification_result')
    # ### end Alembic commands ###
